tekton - tasks - add set-tag-from-version-file feature with path-to-version-file parameter to build-and-push-docker-image and deploy-local-helm-chart tasks

diff --git a/tekton_ci/tasks/build-and-push-docker-image.yml b/tekton_ci/tasks/build-and-push-docker-image.yml
--- a/tekton_ci/tasks/build-and-push-docker-image.yml
+++ b/tekton_ci/tasks/build-and-push-docker-image.yml
@@ -19,6 +19,12 @@ spec:
     - name: push-image-tag
       description: Tag to apply to the built image
       default: "latest"
+    - name: set-tag-from-version-file
+      description: Should the docker image tag be set from a version file (see path-to-version-file variable)
+      default: "false"
+    - name: path-to-version-file
+      description: A path to the file containing the app version number (used with set-tag-from-version-file)
+      default: ""
     - name: extra-build-args
       description: You can provide a list of additional build args here
       default: ""
@@ -83,12 +89,33 @@ spec:
         CONTEXT="$(params.path-to-context)"
         DOCKERFILE="$(params.path-to-dockerfile-within-context)"
         EXTRA_BUILD_ARGS="$(params.extra-build-args)"
-        DESTINATION="$(params.push-image-url):$(params.push-image-tag)"
+        SET_TAG_FROM_VERSION_FILE="$(params.set-tag-from-version-file)"
+        PATH_TO_VERSION_FILE="$(params.path-to-version-file)"
 
         echo "DOCKER_CONFIG_FILE: $DOCKER_CONFIG_FILE"
         echo "CONTEXT: $CONTEXT"
         echo "DOCKERFILE: $DOCKERFILE"
-        echo "EXTRA_BUILD_ARGS: $EXTRA_BUILD_ARGS"
+        echo "SET_TAG_FROM_VERSION_FILE: $SET_TAG_FROM_VERSION_FILE"
+        echo "PATH_TO_VERSION_FILE: $PATH_TO_VERSION_FILE"
+        echo "###############"
+
+        TAG="$(params.push-image-tag)"
+
+        if [[ "$SET_TAG_FROM_VERSION_FILE" == "true" ]]; then
+          echo "Setting tag from version file ..."
+          if [[ "$PATH_TO_VERSION_FILE" == "" ]]; then
+            echo "Configuration ERROR: No path-to-version-file parameter is configured - Aborting build"
+            exit 1
+          fi
+          TAG="$(cat $PATH_TO_VERSION_FILE)"
+          if [[ "$TAG" == "" ]]; then
+            echo "ERROR: Version file at $PATH_TO_VERSION_FILE did not contain data - Aborting build"
+            exit 1
+          fi
+        fi
+
+        echo "Pushing tag: $TAG"
+        DESTINATION="$(params.push-image-url):$TAG"
         echo "DESTINATION: $DESTINATION"
         echo "###############"
 
diff --git a/tekton_ci/tasks/deploy-local-helm-chart.yml b/tekton_ci/tasks/deploy-local-helm-chart.yml
--- a/tekton_ci/tasks/deploy-local-helm-chart.yml
+++ b/tekton_ci/tasks/deploy-local-helm-chart.yml
@@ -27,6 +27,12 @@ spec:
     - name: docker-image-tag
       description: Tag to use for the deployment
       default: "latest"
+    - name: set-tag-from-version-file
+      description: Should the docker image tag be set from a version file (see path-to-version-file variable)
+      default: "false"
+    - name: path-to-version-file
+      description: A path to the file containing the app version number (used with set-tag-from-version-file)
+      default: ""
     - name: path-to-chart
       description: The path to the helm chart that should be deployed
     - name: helm-deployment-name
@@ -66,7 +72,10 @@ spec:
         HELM_DEPLOYMENT_NAME="$(params.helm-deployment-name)"
         DOCKER_IMAGE_URL="$(params.docker-image-url)"
         DOCKER_IMAGE_TAG="$(params.docker-image-tag)"
+        SET_TAG_FROM_VERSION_FILE="$(params.set-tag-from-version-file)"
+        PATH_TO_VERSION_FILE="$(params.path-to-version-file)"
         HELM_TIMEOUT="$(params.helm-timeout)"
+
 
         echo "########################"
         echo "Parameters:"
@@ -75,6 +84,8 @@ spec:
         echo "app-name: $APP_NAME"
         echo "docker-image-url: $DOCKER_IMAGE_URL"
         echo "docker-image-tag: $DOCKER_IMAGE_TAG"
+        echo "set-tag-from-version-file: $SET_TAG_FROM_VERSION_FILE"
+        echo "path-to-version-file: $PATH_TO_VERSION_FILE"
         echo "path-to-configuration: $PATH_TO_CONFIGURATION"
         echo "path-to-chart: $PATH_TO_CHART"
         echo "helm-deployment-name: $HELM_DEPLOYMENT_NAME"
@@ -83,8 +94,24 @@ spec:
         echo "Helm version:"
         helm version
         echo "########################"
-        echo ""
 
+
+        if [[ "$SET_TAG_FROM_VERSION_FILE" == "true" ]]; then
+          echo "Setting tag from version file ..."
+          if [[ "$PATH_TO_VERSION_FILE" == "" ]]; then
+            echo "Configuration ERROR: No path-to-version-file parameter is defined - Aborting build"
+            exit 1
+          fi
+          DOCKER_IMAGE_TAG="$(cat $PATH_TO_VERSION_FILE)"
+          if [[ "$DOCKER_IMAGE_TAG" == "" ]]; then
+            echo "ERROR: Version file at $PATH_TO_VERSION_FILE did not contain data - Aborting build"
+            exit 1
+          fi
+        fi
+        echo "Using Docker image tag: $DOCKER_IMAGE_TAG"
+
+        echo "########################"
+        echo ""
         cd "$PATH_TO_CHART"
         echo "CURRENT PATH: $(pwd)"
 
